import React, { useState } from 'react'; import { createRoot } from 'react-dom/client'; import { Search, Plus, ArrowLeft, Car, Pencil, Save, X, LoaderCircle } from 'lucide-react'; import './styles.css';
type RecordData = { id: string; timestamp: string; prefix: string; name: string; phone: string; department: string; unit: string; plate: string; model: string; type: string; color: string; no: string };
const seed: RecordData[] = [{ id: 'CAR-DEMO-001', timestamp: '2026-08-25 10:30:00', prefix: 'นาย', name: 'สมชาย ใจดี', phone: '0812345678', department: 'วิทยาศาสตร์', unit: '', plate: 'กจ8739', model: 'Toyota Yaris', type: 'รถยนต์', color: 'ขาว', no: '001' }, { id: 'CAR-DEMO-002', timestamp: '2026-08-25 11:00:00', prefix: 'นาง', name: 'สมหญิง รักดี', phone: '0898765432', department: '', unit: 'ศูนย์บริการ', plate: '7กข7301', model: 'Honda City', type: 'รถยนต์', color: 'ดำ', no: '002' }];
const fields: [keyof RecordData, string][] = [['prefix', 'คำนำหน้า'], ['name', 'ชื่อ-นามสกุล'], ['phone', 'หมายเลขโทรศัพท์'], ['department', 'กลุ่มสาระการเรียนรู้'], ['unit', 'หน่วยงาน/ศูนย์'], ['plate', 'หมายเลขทะเบียนรถ'], ['model', 'ยี่ห้อ/รุ่น'], ['type', 'ประเภทรถ'], ['color', 'สีรถ'], ['no', 'NO.']];
const norm = (v: string) => v.toLocaleLowerCase('th-TH').trim().replace(/[\s-]/g, '');
const API_URL = import.meta.env.VITE_API_URL as string | undefined;
const fromSheet = (r: Record<string, string>): RecordData => ({ id: String(r.id || ''), timestamp: String(r['ประทับเวลา'] || r.timestamp || ''), prefix: String(r['คำนำหน้า'] || r.prefix || ''), name: String(r['ชื่อ-นามสกุล'] || r.name || ''), phone: String(r['หมายเลขโทรศัพท์'] || r.phone || ''), department: String(r['กลุ่มสาระการเรียนรู้'] || r.department || ''), unit: String(r['หน่วยงาน/ศูนย์'] || r.unit || ''), plate: String(r['หมายเลขทะเบียนรถ'] || r.plate || ''), model: String(r['ยี่ห้อ/รุ่น'] || r.model || ''), type: String(r['ประเภทรถ'] || r.type || ''), color: String(r['สีรถ'] || r.color || ''), no: String(r['NO.'] || r.no || '') });
const api = async (path: string, options?: RequestInit) => { if (!API_URL) throw new Error('ยังไม่ได้ตั้งค่า VITE_API_URL'); const response = await fetch(`${API_URL}${path}`, options); if (!response.ok) throw new Error('เชื่อมต่อ API ไม่สำเร็จ'); const result = await response.json(); if (result.ok === false) throw new Error(result.error || 'API error'); return result; };
function App() {
    const [records, setRecords] = useState(seed); const [q, setQ] = useState(''); const [results, setResults] = useState<RecordData[] | null>(null); const [selected, setSelected] = useState<RecordData | null>(null); const [mode, setMode] = useState<'search' | 'form'>('search'); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
    const search = async () => { setLoading(true); setError(''); try { const result = await api(`?action=search&q=${encodeURIComponent(q)}`); setResults((result.data || []).map(fromSheet)); } catch (e) { setError(e instanceof Error ? e.message : 'ไม่สามารถค้นหาข้อมูลได้'); setResults([]); } finally { setLoading(false); } };
    const openAdd = () => { setSelected(null); setEditing(false); setMode('form') }; const save = async (data: RecordData) => { setLoading(true); setError(''); try { const action = editing ? 'update' : 'create'; const result = await api('', { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ action, id: data.id, data }) }); const saved = result.data ? fromSheet(result.data) : data; setRecords(rs => editing ? rs.map(r => r.id === saved.id ? saved : r) : [...rs, saved]); setMode('search'); setResults(null); setSelected(null); } catch (e) { setError(e instanceof Error ? e.message : 'ไม่สามารถบันทึกข้อมูลได้'); } finally { setLoading(false); } };
    return <main><header><div className="brand"><Car /> <span>ระบบค้นหาข้อมูลรถ</span></div>{(mode === 'form' || selected) && <button className="iconBtn" onClick={() => { setMode('search'); setSelected(null) }}><ArrowLeft />กลับ</button>}</header><section className="container">{mode === 'form' ? <Form initial={selected ?? undefined} onSave={save} onCancel={() => setMode('search')} loading={loading} /> : selected ? <Detail data={selected} onEdit={() => { setEditing(true); setMode('form') }} /> : <><div className="hero"><p className="eyebrow">VEHICLE REGISTRATION</p><h1>ค้นหาข้อมูลรถ</h1><p className="muted">ค้นหาชื่อ เบอร์โทรศัพท์ ทะเบียนรถ หรือยี่ห้อรถ</p><form onSubmit={e => { e.preventDefault(); search() }} className="searchbar"><Search /><input value={q} onChange={e => setQ(e.target.value)} placeholder="เช่น กจ8739 หรือ 73" aria-label="คำค้นหา" /><button disabled={loading}>{loading ? <LoaderCircle className="spin" /> : <Search />}ค้นหา</button></form><button className="secondary full" onClick={openAdd}><Plus />เพิ่มข้อมูล</button></div>{results && <Results data={results} query={q} onSelect={setSelected} onAdd={openAdd} />}</>}</section></main>
}
function Results({ data, query, onSelect, onAdd }: { data: RecordData[]; query: string; onSelect: (r: RecordData) => void; onAdd: () => void }) { if (!data.length) return <div className="empty"><div className="emptyIcon">?</div><h2>ไม่พบข้อมูล</h2><p>ไม่พบข้อมูลที่ตรงกับ “{query}”</p><button onClick={onAdd}><Plus />เพิ่มข้อมูลใหม่</button></div>; return <div className="results"><h2>พบข้อมูล {data.length} รายการ</h2>{data.map(r => <button className="card" key={r.id} onClick={() => onSelect(r)}><div><strong><Car /> {r.plate || 'ไม่ระบุทะเบียน'}</strong><span>{r.prefix}{r.name}</span><small>{r.model || '-'} • สี{r.color || '-'}</small></div><span className="arrow">›</span></button>)}</div> }
function Detail({ data, onEdit }: { data: RecordData; onEdit: () => void }) { return <div className="detail"><div className="titleRow"><div><p className="eyebrow">DETAIL</p><h1>{data.plate}</h1></div><button className="secondary" onClick={onEdit}><Pencil />แก้ไข</button></div><div className="detailGrid">{fields.map(([k, label]) => <div className="detailItem" key={k}><label>{label}</label><p>{data[k] || '-'}</p></div>)}<div className="detailItem"><label>ประทับเวลา</label><p>{data.timestamp}</p></div></div></div> }
function Form({ initial, onSave, onCancel, loading }: { initial?: RecordData; onSave: (r: RecordData) => void; onCancel: () => void; loading: boolean }) { const [d, setD] = useState<RecordData>(initial ?? { id: '', timestamp: '', prefix: '', name: '', phone: '', department: '', unit: '', plate: '', model: '', type: '', color: '', no: '' }); const [errors, setErrors] = useState<string[]>([]); const update = (k: keyof RecordData, v: string) => setD(x => ({ ...x, [k]: v })); const submit = (e: React.FormEvent) => { e.preventDefault(); const es = []; if (!d.name.trim()) es.push('name'); if (!d.plate.trim()) es.push('plate'); if (d.phone && !/^[0-9+\-\s]{8,15}$/.test(d.phone)) es.push('phone'); setErrors(es); if (!es.length) onSave(d) }; return <form className="form" onSubmit={submit}><div className="titleRow"><div><p className="eyebrow">{initial ? 'EDIT' : 'NEW RECORD'}</p><h1>{initial ? 'แก้ไขข้อมูล' : 'เพิ่มข้อมูล'}</h1></div></div>{fields.map(([k, label]) => <label className="inputLabel" key={k}>{label}{['name', 'plate'].includes(k) && <em>*</em>}<input value={d[k]} onChange={e => update(k, e.target.value)} className={errors.includes(k) ? 'invalid' : ''} />{errors.includes(k) && <small className="error">{k === 'phone' ? 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง' : 'กรุณากรอกข้อมูลนี้'}</small>}</label>)}<div className="actions"><button type="button" className="secondary" onClick={onCancel}><X />ยกเลิก</button><button disabled={loading}>{loading ? <LoaderCircle className="spin" /> : <Save />}บันทึก</button></div></form> }
createRoot(document.getElementById('root')!).render(<App />);
